import type { Metadata } from "next";
import { Geist, Nunito } from "next/font/google";
import "./globals.css";
import { Header } from "@/features/provider/header";
import { QueryProvider } from "@/features/provider/query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${nunito.variable} h-full antialiased`}>
      <Header />
      <body className="container mx-auto">
        <QueryProvider>
          <main className="min-h-screen bg-background text-foreground">
            {children}
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
